### PR TITLE
nalgebra support

### PR DESCRIPTION
**Pull request by imgeorgiev**
Part PR, part discussion how to best do this

A while ago when I was using this awesome crate, I couldn't get it to natively work with nalgebra. The fault is possibly nalgebra's because it doesn't support the more generic `num_traits` crate. Regardless of that, I'd love to just be able to use this crate directly so I'm opening this PR. However, I am not sure if it is the best idea to force `bspline` users to use `nalgebra` since it also limits. I was thinking maybe it would be best to add an `nalgebra` feature to this crate which when enabled, swaps out `num_traits` for `nalgebra`. What do you think?

### CODE REVIEW

**Comment by Twinklebear** [comment]
Cool, yeah I think adding an `nalgebra` feature that swaps out `num_traits` for `nalgebra` would be a great solution. Then we can keep the more general `num_traits` as the default, but folks using `nalgebra` and pick that feature and it'll work with `nalgebra` as well

**Comment by imgeorgiev** [comment]
@Twinklebear this should work nicely. I found the cool crate `trait-set` which minimises code duplication. Also split up some of the tests just to keep things cleaner and leaner :)

**Comment by Twinklebear** [comment]
Thanks @imgeorgiev , this looks good! I was building it locally to try it out and resolve the conflict and wanted to check some changes I made with you:

- I was getting a build error w/ nalgebra version 0.3 where it was failing to build nalgebra with an error:
```
   Compiling nalgebra v0.3.2
error[E0432]: unresolved import `rand::Rand`
 --> /Users/will/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.3.2/src/structs/dmat.rs:9:18
  |
9 | use rand::{self, Rand};
  |                  ^^^^ no `Rand` in the root
```
It looks like nalgebra is at version 0.30 on crates, so I was guessing this is a typo. Moving to 0.30 fixed this

- I made some small tweaks to the `trait_set` use to remove the `num_traits` one when building with nalgebra-support since I was getting a redefinition error about the `Float` trait. So it'll now remove the `num_traits` one when you build w/ nalgebra support:
```rust
extern crate num_traits;
#[cfg(not(feature = "nalgebra-support"))]
trait_set! {
    pub trait Float = num_traits::Float;
}

#[cfg(feature = "nalgebra-support")]
extern crate nalgebra;
#[cfg(feature = "nalgebra-support")]
trait_set! {
    pub trait Float = nalgebra::RealField ;
}
```

- I also found that I had to add the `Copy` trait to the nalgebra version of the `Float` trait, it seems like `nalgebra::RealField` isn't `Copy` by default. So it's:
```rust
#[cfg(feature = "nalgebra-support")]
trait_set! {
    pub trait Float = nalgebra::RealField + Copy;
}
```

After making those tweaks I can build and run the tests, which pass in both the `nalgebra` and `num_traits` modes, so it looks like everything's ok, but I wanted to double check these with you. If that all sounds good I'll merge this in

**Comment by Twinklebear** [comment]
This is now released as 1.1.0 on crates.io . Thanks @imgeorgiev !

**Comment by imgeorgiev** [comment]
Sorry @Twinklebear was a bit busy and missed the email about your comment. All looks and compiles on my machine. No idea where I got the nalgebra `v0.3.2` from :D

**Comment by Twinklebear** [comment]
No worries! 👍

**Pull request merged**
